layout_spectrum: 0.881847
typography_spectrum: 0.4946237
color:
  saturation: 0.02245244
  lightness: 0.6441773
  brandStrength: 0.7632576
  brandColors:
    - '#FFFFFF'
    - '#016D56'
    - '#020203'
    - '#C4C5C8'
    - '#65A294'
  rhythmicContrast: 0.137238
name: www.suttoncabs.co.uk
